"""
Django settings for pinterest project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

from django.conf.global_settings import AUTHENTICATION_BACKENDS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o$6&9lvbi9c(09phy$r+sp4n5al$b9_&*qi$25$-qmdon)lreo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['mysite.com', 'localhost', '127.0.0.1']

SITE_URL = 'http://localhost:8000'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'image.apps.ImageConfig',
    'user.apps.UserConfig',
    'action.apps.ActionConfig',
    'djoser',
    'django_extensions',
    'taggit',
    'django_filters',

]

AUTH_USER_MODEL = 'user.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 16,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ]
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

DJOSER = {
    'PASSWORD_RESET_CONFIRM_URL': '#/password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': '#/username/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': '#/activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': True,
    'SERIALIZERS': {
        'user_create': 'user.serializers.CustomUserCreateSerializer',
    }
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=35),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'pinterest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pinterest.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'eldar00319g@gmail.com'
EMAIL_HOST_PASSWORD = 'bjel hudd yxge fvyd'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CELERY_BROKER_URL = 'amqp://guest:guest@localhost:5672/'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

CELERY_TASK_ROUTES = {
    'image.tasks.generate_thumbnail': {'queue': 'queue1'},
    'image.tasks.generate_image_tags': {'queue': 'queue1'},
    'image.tasks.post_image': {'queue': 'queue2'},
    'image.tasks.send_notification_email': {'queue': 'queue2'},
}
CELERY_RESULT_EXPIRES = 7200

REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 1


# https://accounts.google.com/o/oauth2/v2/auth?client_id=450086810881-na3qicdtjk5oc2nknr3ffpfscb6ii7b4.apps.googleusercontent.com&redirect_uri=https://mysite.com:8000/auth/complete/google-oauth2/&response_type=token&scope=email profile


# https://accounts.google.com/o/oauth2/v2/auth?client_id=450086810881-na3qicdtjk5oc2nknr3ffpfscb6ii7b4.apps.googleusercontent.com&redirect_uri=http://127.0.0.1:8000/auth/complete/google-oauth2/&response_type=token&scope=email profile

#ya29.a0AXeO80ShsAbSkY4aB6C_xbXBlbtcb1QaHLzKi8x_Qv8VGaI-FDR3kotuHnHR-4HJnbI7X6lBXSc62WU7zb0N_87_YTmfvhVzWm5DE9tV17suZce2bayh3OQOt_5fWOiM8QwwPB_puhi0ac4U1zTJ8t6A0VjA0owkxx8aCgYKAc4SARASFQHGX2MiRe0AtS6TgV6xpzjmGSULrA0170

# curl -k --request POST --url https://mysite.com:8000/auth/google/ --header "Content-Type: application/json" --data "{\"access_token\": \"ya29.a0AXeO80SJrhio9rqUAl2iUQYljjiTSqvAwI4jEkHNX5Dm6Z5A0TySsJRBnoX_Fm7uLfeBe3JgV3Npobd1b2MxBu5ydtrr5dzcXg2Q6MtECURcKk8-xnK0rcJZCBwj_wATOLE4EUSLQL6f-57LgJuot-G3RYgJxh7m_yVNa_yMGAaCgYKAVkSARASFQHGX2MiRdc1EoXLdddvWmxE37X1mg0177\"}"