# Generated by Django 4.2.17 on 2025-01-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_image_total_likes_image_users_like_1'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_owner_image_comment',
        ),
    ]
