# Generated by Django 4.2.17 on 2025-01-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_remove_comment_unique_owner_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_open_liked_images',
            field=models.BooleanField(default=False),
        ),
    ]
