# Generated by Django 4.2.17 on 2025-01-31 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0006_image_is_open_liked_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='liked_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
