# Generated by Django 4.2.17 on 2025-01-31 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_alter_image_users_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_open_liked_images',
        ),
    ]
