# Generated by Django 4.2.17 on 2025-02-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0010_alter_image_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='image_categ_name_4114fe_idx')],
            },
        ),
    ]
