# Generated by Django 4.2.17 on 2025-01-29 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='user.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
