# Generated by Django 4.2.17 on 2025-01-29 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', through='user.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
