# Generated by Django 4.2.17 on 2025-01-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_follow_unique_follow_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_open_liked_images',
            field=models.BooleanField(default=False),
        ),
    ]
